2024-03-21T07:52:52 {"cpu": 2.67138671875, "cpu_total": 8, "cpu_usage": 0.33392333984375, "memory": 1919.0, "memory_total": 8865.0, "memory_usage": 0.2164692611393119, "pipeline_run_id": 6168, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "level": "INFO", "message": "Pipeline etl_pipeline for run 6168 in schedule 3 is alive.", "timestamp": 1711007572.050244, "uuid": "e62f10e856f947ba8dc2e3ab020a49e0"}
2024-03-21T07:52:52 {"cpu": 2.67138671875, "cpu_total": 8, "cpu_usage": 0.33392333984375, "memory": 1937.0, "memory_total": 8865.0, "memory_usage": 0.21849971799210377, "pipeline_run_id": 6168, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "level": "INFO", "message": "Pipeline etl_pipeline for run 6168 in schedule 3 is alive.", "timestamp": 1711007572.144403, "uuid": "1b10017e2c3646c499ecdb96355ee2f7"}
2024-03-21T07:52:53 {"block_run_id": 18499, "block_uuid": "api_load_data", "pipeline_run_id": 6168, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "level": "INFO", "message": "Execute PipelineRun 6168, BlockRun 18499: pipeline etl_pipeline block api_load_data", "timestamp": 1711007573.117895, "uuid": "cc19987cb990403ab44c6be88dc4078f"}
2024-03-21T07:52:53 {"block_run_id": 18499, "block_uuid": "api_load_data", "pipeline_run_id": 6168, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "level": "INFO", "message": "BlockRun 18499 (block_uuid: api_load_data) completes.", "timestamp": 1711007573.686365, "uuid": "f4263914fe2e4095b5cabec15db07c9a"}
2024-03-21T07:53:01 {"cpu": 2.66357421875, "cpu_total": 8, "cpu_usage": 0.33294677734375, "memory": 1929.0, "memory_total": 8865.0, "memory_usage": 0.21759729272419628, "pipeline_run_id": 6168, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "level": "INFO", "message": "Pipeline etl_pipeline for run 6168 in schedule 3 is alive.", "timestamp": 1711007581.350666, "uuid": "7060892fde2b4a368736d59fbf22515d"}
2024-03-21T07:53:02 {"block_run_id": 18500, "block_uuid": "transform_data", "pipeline_run_id": 6168, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "level": "INFO", "message": "Execute PipelineRun 6168, BlockRun 18500: pipeline etl_pipeline block transform_data", "timestamp": 1711007582.403743, "uuid": "68ceb8ca55ff4409b618027b4058a07a"}
2024-03-21T07:53:02 {"block_run_id": 18500, "block_uuid": "transform_data", "pipeline_run_id": 6168, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "level": "INFO", "message": "BlockRun 18500 (block_uuid: transform_data) completes.", "timestamp": 1711007582.477363, "uuid": "e1c1997a76314699b961e440f91f340d"}
2024-03-21T07:53:11 {"cpu": 2.66162109375, "cpu_total": 8, "cpu_usage": 0.33270263671875, "memory": 1939.0, "memory_total": 8865.0, "memory_usage": 0.21872532430908065, "pipeline_run_id": 6168, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "level": "INFO", "message": "Pipeline etl_pipeline for run 6168 in schedule 3 is alive.", "timestamp": 1711007591.558872, "uuid": "1de5a93b4acf4b91b7cd2ab804fe6707"}
2024-03-21T07:53:12 {"block_run_id": 18501, "block_uuid": "export_to_postgres", "pipeline_run_id": 6168, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "level": "INFO", "message": "Execute PipelineRun 6168, BlockRun 18501: pipeline etl_pipeline block export_to_postgres", "timestamp": 1711007592.639339, "uuid": "9c6780c1071343bb88eae2ae8b61eb9a"}
2024-03-21T07:53:12 {"block_run_id": 18501, "block_uuid": "export_to_postgres", "pipeline_run_id": 6168, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "level": "EXCEPTION", "message": "BlockRun 18501 (block_uuid: export_to_postgres) failed.", "timestamp": 1711007592.737463, "uuid": "63cb9623b68e4fed9e0c1526686f0134", "error": ["Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 613, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 588, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1077, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1314, in execute_sync\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1223, in execute_sync\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1529, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1685, in _execute_block\n    outputs = self.execute_block_function(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1724, in execute_block_function\n    output = block_function_updated(*input_vars, **global_vars)\n  File \"<string>\", line 25, in export_data_to_postgres\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/sql.py\", line 279, in export\n    df = clean_df_for_export(df, self.clean, dtypes)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/export_utils.py\", line 90, in clean_df_for_export\n    copy_df = df.copy()\nAttributeError: 'int' object has no attribute 'copy'\n"], "error_stack": [["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 163, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 743, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 87, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 50, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1643, in schedule_all\n    PipelineScheduler(r).schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 157, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 318, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 602, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 28, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 108, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 183, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 288, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 253, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1152, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 641, in execute\n    on_failure(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 157, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 433, in on_block_failure\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 65, in __send_message\n    data['error_stack'] = traceback.format_stack(),\n"]], "error_stacktrace": ["'int' object has no attribute 'copy'"]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 613, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 588, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1077, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1314, in execute_sync
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1223, in execute_sync
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1529, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1685, in _execute_block
    outputs = self.execute_block_function(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1724, in execute_block_function
    output = block_function_updated(*input_vars, **global_vars)
  File "<string>", line 25, in export_data_to_postgres
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/sql.py", line 279, in export
    df = clean_df_for_export(df, self.clean, dtypes)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/export_utils.py", line 90, in clean_df_for_export
    copy_df = df.copy()
AttributeError: 'int' object has no attribute 'copy'
2024-03-21T07:53:21 {"cpu": 2.67578125, "cpu_total": 8, "cpu_usage": 0.33447265625, "memory": 1888.0, "memory_total": 8865.0, "memory_usage": 0.21297236322617033, "pipeline_run_id": 6168, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "level": "INFO", "message": "Pipeline etl_pipeline for run 6168 in schedule 3 is alive.", "timestamp": 1711007601.716129, "uuid": "fd38636eb0c74b46859fc96f5fe4dfe6"}
2024-03-21T07:58:41 {"cpu": 2.62451171875, "cpu_total": 8, "cpu_usage": 0.32806396484375, "memory": 1965.0, "memory_total": 8865.0, "memory_usage": 0.22165820642978004, "pipeline_run_id": 6175, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "level": "INFO", "message": "Pipeline etl_pipeline for run 6175 in schedule 3 is alive.", "timestamp": 1711007921.218845, "uuid": "9e8ebe7aa5514366b99755b96c0c63da"}
2024-03-21T07:58:41 {"cpu": 2.62451171875, "cpu_total": 8, "cpu_usage": 0.32806396484375, "memory": 1979.0, "memory_total": 8865.0, "memory_usage": 0.22323745064861816, "pipeline_run_id": 6175, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "level": "INFO", "message": "Pipeline etl_pipeline for run 6175 in schedule 3 is alive.", "timestamp": 1711007921.314577, "uuid": "2c7f13ee14734da988c018aca61beb9f"}
2024-03-21T07:58:42 {"block_run_id": 18520, "block_uuid": "api_load_data", "pipeline_run_id": 6175, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "level": "INFO", "message": "Execute PipelineRun 6175, BlockRun 18520: pipeline etl_pipeline block api_load_data", "timestamp": 1711007922.280518, "uuid": "853e15ffc8d24f00a6902cc3886a83a3"}
2024-03-21T07:58:42 {"block_run_id": 18520, "block_uuid": "api_load_data", "pipeline_run_id": 6175, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "level": "INFO", "message": "BlockRun 18520 (block_uuid: api_load_data) completes.", "timestamp": 1711007922.491719, "uuid": "e3e6ee7bfde44fa8a83a0f009ce10723"}
2024-03-21T07:58:51 {"cpu": 2.61767578125, "cpu_total": 8, "cpu_usage": 0.32720947265625, "memory": 1968.0, "memory_total": 8865.0, "memory_usage": 0.22199661590524536, "pipeline_run_id": 6175, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "level": "INFO", "message": "Pipeline etl_pipeline for run 6175 in schedule 3 is alive.", "timestamp": 1711007931.477359, "uuid": "cd7fbcf2aa89497689929166f50b37bc"}
2024-03-21T07:58:52 {"block_run_id": 18521, "block_uuid": "transform_data", "pipeline_run_id": 6175, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "level": "INFO", "message": "Execute PipelineRun 6175, BlockRun 18521: pipeline etl_pipeline block transform_data", "timestamp": 1711007932.523714, "uuid": "79e65472c3444e61a0988c2a716172ed"}
2024-03-21T07:58:52 {"block_run_id": 18521, "block_uuid": "transform_data", "pipeline_run_id": 6175, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "level": "INFO", "message": "BlockRun 18521 (block_uuid: transform_data) completes.", "timestamp": 1711007932.637983, "uuid": "180369ac2f8046ce8aaab93a289b6a53"}
2024-03-21T07:59:01 {"cpu": 2.60546875, "cpu_total": 8, "cpu_usage": 0.32568359375, "memory": 1977.0, "memory_total": 8865.0, "memory_usage": 0.22301184433164128, "pipeline_run_id": 6175, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "level": "INFO", "message": "Pipeline etl_pipeline for run 6175 in schedule 3 is alive.", "timestamp": 1711007941.699869, "uuid": "b587587877794ab8b981e1fa6c05a827"}
2024-03-21T07:59:02 {"block_run_id": 18522, "block_uuid": "export_to_postgres", "pipeline_run_id": 6175, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "level": "INFO", "message": "Execute PipelineRun 6175, BlockRun 18522: pipeline etl_pipeline block export_to_postgres", "timestamp": 1711007942.759405, "uuid": "0d6686e9a4934944a929890ff3c411bf"}
2024-03-21T07:59:02 {"block_run_id": 18522, "block_uuid": "export_to_postgres", "pipeline_run_id": 6175, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "level": "INFO", "message": "BlockRun 18522 (block_uuid: export_to_postgres) completes.", "timestamp": 1711007942.904951, "uuid": "3266da3ed7ff449f86c9ab38b846e1ba"}
2024-03-21T07:59:11 {"cpu": 2.6044921875, "cpu_total": 8, "cpu_usage": 0.3255615234375, "memory": 1932.0, "memory_total": 8865.0, "memory_usage": 0.2179357021996616, "pipeline_run_id": 6175, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "level": "INFO", "message": "Pipeline etl_pipeline for run 6175 in schedule 3 is alive.", "timestamp": 1711007951.912333, "uuid": "256f35c626d548b6a79cb01566e41f2a"}
