2024-03-21T07:52:51 {"cpu": 2.67138671875, "cpu_total": 8, "cpu_usage": 0.33392333984375, "memory": 1885.0, "memory_total": 8865.0, "memory_usage": 0.212633953750705, "pipeline_run_id": 6167, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "level": "INFO", "message": "Pipeline etl_pipeline for run 6167 in schedule 3 is alive.", "timestamp": 1711007571.973238, "uuid": "b8264afa22674ae996e55a5d1293a727"}
2024-03-21T07:52:52 {"block_run_id": 18496, "block_uuid": "api_load_data", "pipeline_run_id": 6167, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "level": "INFO", "message": "Execute PipelineRun 6167, BlockRun 18496: pipeline etl_pipeline block api_load_data", "timestamp": 1711007572.06769, "uuid": "f8043a1ea6b34a89b9a81cf9fdcd193a"}
2024-03-21T07:52:52 {"cpu": 2.67138671875, "cpu_total": 8, "cpu_usage": 0.33392333984375, "memory": 1935.0, "memory_total": 8865.0, "memory_usage": 0.2182741116751269, "pipeline_run_id": 6167, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "level": "INFO", "message": "Pipeline etl_pipeline for run 6167 in schedule 3 is alive.", "timestamp": 1711007572.108404, "uuid": "fefea36971e240df944d679c2e22e990"}
2024-03-21T07:52:52 {"block_run_id": 18496, "block_uuid": "api_load_data", "pipeline_run_id": 6167, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "level": "INFO", "message": "BlockRun 18496 (block_uuid: api_load_data) completes.", "timestamp": 1711007572.629363, "uuid": "5f192531bb494afdbdd935e53d76d7e1"}
2024-03-21T07:53:01 {"cpu": 2.66357421875, "cpu_total": 8, "cpu_usage": 0.33294677734375, "memory": 1890.0, "memory_total": 8865.0, "memory_usage": 0.2131979695431472, "pipeline_run_id": 6167, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "level": "INFO", "message": "Pipeline etl_pipeline for run 6167 in schedule 3 is alive.", "timestamp": 1711007581.288973, "uuid": "81206cc2575642339a223a11fef58f6a"}
2024-03-21T07:53:01 {"block_run_id": 18497, "block_uuid": "transform_data", "pipeline_run_id": 6167, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "level": "INFO", "message": "Execute PipelineRun 6167, BlockRun 18497: pipeline etl_pipeline block transform_data", "timestamp": 1711007581.374348, "uuid": "45b2d2765c924fd19b6183fa2a605d26"}
2024-03-21T07:53:01 {"block_run_id": 18497, "block_uuid": "transform_data", "pipeline_run_id": 6167, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "level": "INFO", "message": "BlockRun 18497 (block_uuid: transform_data) completes.", "timestamp": 1711007581.44874, "uuid": "0089018b4cd64497ae776bb625eca34b"}
2024-03-21T07:53:11 {"cpu": 2.66162109375, "cpu_total": 8, "cpu_usage": 0.33270263671875, "memory": 1897.0, "memory_total": 8865.0, "memory_usage": 0.21398759165256628, "pipeline_run_id": 6167, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "level": "INFO", "message": "Pipeline etl_pipeline for run 6167 in schedule 3 is alive.", "timestamp": 1711007591.489378, "uuid": "018d4612c37a457c99a929bec53f48d8"}
2024-03-21T07:53:11 {"block_run_id": 18498, "block_uuid": "export_to_postgres", "pipeline_run_id": 6167, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "level": "INFO", "message": "Execute PipelineRun 6167, BlockRun 18498: pipeline etl_pipeline block export_to_postgres", "timestamp": 1711007591.583308, "uuid": "a80e1b20a8dd421682037e97fbdd1034"}
2024-03-21T07:53:11 {"block_run_id": 18498, "block_uuid": "export_to_postgres", "pipeline_run_id": 6167, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "level": "EXCEPTION", "message": "BlockRun 18498 (block_uuid: export_to_postgres) failed.", "timestamp": 1711007591.661482, "uuid": "d6159ccf2f6147ccb825ce97ae577900", "error": ["Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 613, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 588, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1077, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1314, in execute_sync\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1223, in execute_sync\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1529, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1685, in _execute_block\n    outputs = self.execute_block_function(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1724, in execute_block_function\n    output = block_function_updated(*input_vars, **global_vars)\n  File \"<string>\", line 25, in export_data_to_postgres\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/sql.py\", line 279, in export\n    df = clean_df_for_export(df, self.clean, dtypes)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/export_utils.py\", line 90, in clean_df_for_export\n    copy_df = df.copy()\nAttributeError: 'int' object has no attribute 'copy'\n"], "error_stack": [["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 163, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 743, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 87, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 50, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1643, in schedule_all\n    PipelineScheduler(r).schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 157, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 318, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 602, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 28, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 108, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 183, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 288, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 253, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1152, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 641, in execute\n    on_failure(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 157, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 433, in on_block_failure\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 65, in __send_message\n    data['error_stack'] = traceback.format_stack(),\n"]], "error_stacktrace": ["'int' object has no attribute 'copy'"]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 613, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 588, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1077, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1314, in execute_sync
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1223, in execute_sync
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1529, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1685, in _execute_block
    outputs = self.execute_block_function(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1724, in execute_block_function
    output = block_function_updated(*input_vars, **global_vars)
  File "<string>", line 25, in export_data_to_postgres
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/sql.py", line 279, in export
    df = clean_df_for_export(df, self.clean, dtypes)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/export_utils.py", line 90, in clean_df_for_export
    copy_df = df.copy()
AttributeError: 'int' object has no attribute 'copy'
2024-03-21T07:53:21 {"cpu": 2.67578125, "cpu_total": 8, "cpu_usage": 0.33447265625, "memory": 1888.0, "memory_total": 8865.0, "memory_usage": 0.21297236322617033, "pipeline_run_id": 6167, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "level": "INFO", "message": "Pipeline etl_pipeline for run 6167 in schedule 3 is alive.", "timestamp": 1711007601.680926, "uuid": "dc8891c6282b43298d9e1d84214ec2da"}
2024-03-21T07:58:41 {"cpu": 2.62451171875, "cpu_total": 8, "cpu_usage": 0.32806396484375, "memory": 1927.0, "memory_total": 8865.0, "memory_usage": 0.2173716864072194, "pipeline_run_id": 6174, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "level": "INFO", "message": "Pipeline etl_pipeline for run 6174 in schedule 3 is alive.", "timestamp": 1711007921.149433, "uuid": "63f89f7f6f744b1cb25dec640a0351c3"}
2024-03-21T07:58:41 {"block_run_id": 18517, "block_uuid": "api_load_data", "pipeline_run_id": 6174, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "level": "INFO", "message": "Execute PipelineRun 6174, BlockRun 18517: pipeline etl_pipeline block api_load_data", "timestamp": 1711007921.237233, "uuid": "58550e4ea9444a05a23c61f74754ae2a"}
2024-03-21T07:58:41 {"cpu": 2.62451171875, "cpu_total": 8, "cpu_usage": 0.32806396484375, "memory": 1977.0, "memory_total": 8865.0, "memory_usage": 0.22301184433164128, "pipeline_run_id": 6174, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "level": "INFO", "message": "Pipeline etl_pipeline for run 6174 in schedule 3 is alive.", "timestamp": 1711007921.277707, "uuid": "8ef65e95c75b40dcb7791bd9e42b83a6"}
2024-03-21T07:58:41 {"block_run_id": 18517, "block_uuid": "api_load_data", "pipeline_run_id": 6174, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "level": "INFO", "message": "BlockRun 18517 (block_uuid: api_load_data) completes.", "timestamp": 1711007921.467237, "uuid": "253104f8115d484db0e5953a56fc5bf5"}
2024-03-21T07:58:51 {"cpu": 2.61767578125, "cpu_total": 8, "cpu_usage": 0.32720947265625, "memory": 1932.0, "memory_total": 8865.0, "memory_usage": 0.2179357021996616, "pipeline_run_id": 6174, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "level": "INFO", "message": "Pipeline etl_pipeline for run 6174 in schedule 3 is alive.", "timestamp": 1711007931.410441, "uuid": "f2584517565b41c49992d4b2d8d6ee75"}
2024-03-21T07:58:51 {"block_run_id": 18518, "block_uuid": "transform_data", "pipeline_run_id": 6174, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "level": "INFO", "message": "Execute PipelineRun 6174, BlockRun 18518: pipeline etl_pipeline block transform_data", "timestamp": 1711007931.501918, "uuid": "4fe7ad2f26844afbaf25fcd944fe4c78"}
2024-03-21T07:58:51 {"block_run_id": 18518, "block_uuid": "transform_data", "pipeline_run_id": 6174, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "level": "INFO", "message": "BlockRun 18518 (block_uuid: transform_data) completes.", "timestamp": 1711007931.617531, "uuid": "639dbe08c5404405b65b73fb5fb5c017"}
2024-03-21T07:59:01 {"cpu": 2.60546875, "cpu_total": 8, "cpu_usage": 0.32568359375, "memory": 1937.0, "memory_total": 8865.0, "memory_usage": 0.21849971799210377, "pipeline_run_id": 6174, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "level": "INFO", "message": "Pipeline etl_pipeline for run 6174 in schedule 3 is alive.", "timestamp": 1711007941.615522, "uuid": "ee98cc75e1ac4c0695b032a9b226ed69"}
2024-03-21T07:59:01 {"block_run_id": 18519, "block_uuid": "export_to_postgres", "pipeline_run_id": 6174, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "level": "INFO", "message": "Execute PipelineRun 6174, BlockRun 18519: pipeline etl_pipeline block export_to_postgres", "timestamp": 1711007941.723947, "uuid": "42e0f370d39d413a839fa573e50e3493"}
2024-03-21T07:59:01 {"block_run_id": 18519, "block_uuid": "export_to_postgres", "pipeline_run_id": 6174, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "level": "INFO", "message": "BlockRun 18519 (block_uuid: export_to_postgres) completes.", "timestamp": 1711007941.879468, "uuid": "8c4c32c72409478bb33ff71c3c0f892b"}
2024-03-21T07:59:11 {"cpu": 2.6044921875, "cpu_total": 8, "cpu_usage": 0.3255615234375, "memory": 1932.0, "memory_total": 8865.0, "memory_usage": 0.2179357021996616, "pipeline_run_id": 6174, "pipeline_schedule_id": 3, "pipeline_uuid": "etl_pipeline", "hostname": "3353dc602115", "level": "INFO", "message": "Pipeline etl_pipeline for run 6174 in schedule 3 is alive.", "timestamp": 1711007951.872451, "uuid": "468bee06b8fe472a9ca9e62005b16dc6"}
